CREATE TABLE theory_lessons (
    id UUID PRIMARY KEY,
    module_id UUID NOT NULL REFERENCES learning_modules(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    title_en VARCHAR(255),
    summary TEXT NOT NULL,
    summary_en TEXT,
    content TEXT NOT NULL,
    content_en TEXT,
    key_concepts TEXT,
    key_concepts_en TEXT,
    common_mistakes TEXT,
    common_mistakes_en TEXT,
    practical_example TEXT,
    practical_example_en TEXT,
    request_example TEXT,
    request_example_en TEXT,
    response_example TEXT,
    response_example_en TEXT,
    related_concepts TEXT,
    related_concepts_en TEXT,
    before_mission TEXT,
    before_mission_en TEXT,
    order_index INT NOT NULL DEFAULT 0,
    reading_time_minutes INT NOT NULL DEFAULT 5,
    related_mission_id UUID REFERENCES missions(id) ON DELETE SET NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO theory_lessons (
    id, module_id, title, title_en, summary, summary_en, 
    content, content_en, key_concepts, key_concepts_en, 
    common_mistakes, common_mistakes_en, practical_example, practical_example_en, 
    request_example, request_example_en, response_example, response_example_en,
    related_concepts, related_concepts_en, before_mission, before_mission_en, 
    order_index, reading_time_minutes, related_mission_id
) VALUES (
    '44444444-4444-4444-4444-000000000001',
    (SELECT id FROM learning_modules WHERE slug = 'o-que-e-uma-api'),
    'O que é uma API?',
    'What is an API?',
    'Entenda o conceito fundamental de APIs, como elas conectam sistemas diferentes e por que são a base da internet moderna.',
    'Understand the fundamental concept of APIs, how they connect different systems, and why they are the foundation of the modern internet.',
    'API significa Application Programming Interface (Interface de Programação de Aplicações). De forma simples, é um contrato de comunicação que permite que dois sistemas diferentes conversem entre si de maneira padronizada. Imagine que você está em um restaurante: você é o cliente, a cozinha é o servidor e o garçom é a API. Você não entra na cozinha para preparar a comida; você faz o pedido ao garçom, que leva a informação até a cozinha e traz o prato pronto de volta para você. No mundo do software, a API recebe a sua requisição (o que você quer), vai até o banco de dados ou regra de negócio (onde a informação está) e traz a resposta de volta. É importante entender que a API NÃO é o banco de dados e também NÃO é uma tela visual. Ela é um serviço invisível para o usuário final, mas essencial para que um aplicativo de celular, um site ou um caixa de supermercado consigam buscar dados em tempo real.',
    'API stands for Application Programming Interface. Simply put, it is a communication contract that allows two different systems to talk to each other in a standardized way. Imagine you are in a restaurant: you are the client, the kitchen is the server, and the waiter is the API. You do not go into the kitchen to prepare the food; you place your order with the waiter, who takes the information to the kitchen and brings the finished dish back to you. In the software world, the API receives your request (what you want), goes to the database or business logic (where the information is), and brings the response back. It is important to understand that the API is NOT the database and is NOT a visual screen. It is an invisible service for the end user, but essential for a mobile app, a website, or a supermarket checkout to fetch data in real time.',
    'Contrato de Comunicação, Cliente-Servidor, Integração de Sistemas, Interoperabilidade',
    'Communication Contract, Client-Server, System Integration, Interoperability',
    'Achar que API é igual a Endpoint (Endpoint é só uma URL específica dentro da API). Confundir API com Banco de Dados. Achar que JSON é a API (JSON é apenas o formato do pacote que a API entrega).',
    'Thinking API is the same as Endpoint (An Endpoint is just a specific URL within an API). Confusing API with a Database. Thinking JSON is the API (JSON is just the format of the package the API delivers).',
    'Quando você abre o aplicativo do Uber, o app do seu celular não tem os dados de todos os motoristas salvos na memória dele. Ele usa uma API para perguntar aos servidores centrais: "Quais motoristas estão perto dessa coordenada GPS?". A API processa e responde com a lista.',
    'When you open the Uber app, the app on your phone does not have the data of all drivers saved in its memory. It uses an API to ask the central servers: "Which drivers are near this GPS coordinate?". The API processes it and replies with the list.',
    'GET /drivers?lat=-23.55&lng=-46.63\nHost: api.uber.com\nAuthorization: Bearer seu_token_aqui',
    'GET /drivers?lat=-23.55&lng=-46.63\nHost: api.uber.com\nAuthorization: Bearer your_token_here',
    '{\n  "status": "success",\n  "drivers_nearby": [\n    {\n      "id": "drv_123",\n      "name": "João",\n      "eta_minutes": 3\n    }\n  ]\n}',
    '{\n  "status": "success",\n  "drivers_nearby": [\n    {\n      "id": "drv_123",\n      "name": "John",\n      "eta_minutes": 3\n    }\n  ]\n}',
    'HTTP, Endpoints, JSON, REST',
    'HTTP, Endpoints, JSON, REST',
    'Na sua primeira missão, você assumirá o papel de cliente e fará um simples "pedido" (uma requisição GET) a uma API simulada para buscar produtos. Lembre-se: você está apenas pedindo dados.',
    'In your first mission, you will take the role of a client and make a simple "order" (a GET request) to a simulated API to fetch products. Remember: you are just asking for data.',
    1,
    6,
    (SELECT id FROM missions WHERE slug = 'primeira-requisicao-get')
);
