-- 1. Request e Response
INSERT INTO theory_lessons (
    id, module_id, title, title_en, summary, summary_en, 
    content, content_en, key_concepts, key_concepts_en, 
    common_mistakes, common_mistakes_en, practical_example, practical_example_en, 
    request_example, request_example_en, response_example, response_example_en,
    related_concepts, related_concepts_en, before_mission, before_mission_en, 
    order_index, reading_time_minutes, related_mission_id
) VALUES (
    '44444444-4444-4444-4444-000000000002',
    (SELECT id FROM learning_modules WHERE slug = 'request-e-response'),
    'O ciclo Request e Response',
    'The Request and Response cycle',
    'Entenda como as informações trafegam na web através do ciclo de perguntas (requisições) e respostas.',
    'Understand how information travels on the web through the cycle of questions (requests) and answers (responses).',
    'Toda a comunicação na web baseada em HTTP funciona em um ciclo de duas vias. O cliente (que pode ser o seu navegador Chrome, um aplicativo de celular ou o Sandbox do IntegraLab) envia uma requisição chamada **Request**. Essa requisição contém o que o cliente quer fazer (o Método), onde quer fazer (o Path), além de informações extras (Headers e Body). O servidor recebe essa requisição, processa e devolve uma **Response**. A response contém o código de status (deu certo? deu erro?), cabeçalhos de resposta e, geralmente, o conteúdo solicitado (como um arquivo HTML ou um JSON com os dados).\n\nA diferença essencial é quem origina a mensagem. O servidor nunca "empurra" dados no modelo HTTP tradicional; ele sempre fica aguardando o cliente fazer a Request primeiro.',
    'All web communication based on HTTP works in a two-way cycle. The client (which could be your Chrome browser, a mobile app, or the IntegraLab Sandbox) sends a request called a **Request**. This request contains what the client wants to do (the Method), where to do it (the Path), plus extra information (Headers and Body). The server receives this request, processes it, and returns a **Response**. The response contains the status code (did it work? did it fail?), response headers, and usually the requested content (like an HTML file or a JSON with data).\n\nThe essential difference is who originates the message. The server never "pushes" data in the traditional HTTP model; it always waits for the client to make the Request first.',
    'Request (Requisição), Response (Resposta), Ciclo HTTP, Cliente-Servidor',
    'Request, Response, HTTP Cycle, Client-Server',
    'Achar que o servidor pode enviar uma Response sem ter recebido uma Request. Não entender que Headers existem tanto na Request quanto na Response, mas com finalidades diferentes.',
    'Thinking the server can send a Response without having received a Request. Not understanding that Headers exist in both the Request and the Response, but with different purposes.',
    'Quando você digita "google.com" no navegador e aperta Enter, seu computador monta uma Request GET para os servidores do Google. O Google recebe isso e devolve uma Response contendo o código HTML da página inicial. O navegador desenha a página pra você.',
    'When you type "google.com" in the browser and press Enter, your computer builds a GET Request to Google servers. Google receives this and returns a Response containing the HTML code of the home page. The browser draws the page for you.',
    'GET / HTTP/1.1\nHost: google.com\nUser-Agent: Mozilla/5.0',
    'GET / HTTP/1.1\nHost: google.com\nUser-Agent: Mozilla/5.0',
    'HTTP/1.1 200 OK\nContent-Type: text/html\n\n<!DOCTYPE html><html>...</html>',
    'HTTP/1.1 200 OK\nContent-Type: text/html\n\n<!DOCTYPE html><html>...</html>',
    'Métodos HTTP, Status Codes',
    'HTTP Methods, Status Codes',
    'Observe as abas de Request e Response no Sandbox. Veja como você sempre preenche o painel esquerdo primeiro, e o painel direito só preenche após a execução.',
    'Observe the Request and Response tabs in the Sandbox. Notice how you always fill the left panel first, and the right panel only fills after execution.',
    1,
    5,
    NULL
);

-- 2. Métodos HTTP
INSERT INTO theory_lessons (
    id, module_id, title, title_en, summary, summary_en, 
    content, content_en, key_concepts, key_concepts_en, 
    common_mistakes, common_mistakes_en, practical_example, practical_example_en, 
    request_example, request_example_en, response_example, response_example_en,
    related_concepts, related_concepts_en, before_mission, before_mission_en, 
    order_index, reading_time_minutes, related_mission_id
) VALUES (
    '44444444-4444-4444-4444-000000000003',
    (SELECT id FROM learning_modules WHERE slug = 'metodos-http'),
    'Métodos HTTP (Verbos)',
    'HTTP Methods (Verbs)',
    'Descubra a diferença entre GET, POST, PUT, PATCH e DELETE e por que usá-los corretamente é essencial.',
    'Discover the difference between GET, POST, PUT, PATCH, and DELETE and why using them correctly is essential.',
    'O Método HTTP (também chamado de verbo) indica a intenção da sua requisição. Pense nele como o comando de ação.\n\n- **GET**: "Me dê essa informação". Usado apenas para leitura. Não deve alterar o banco de dados.\n- **POST**: "Tome essa informação nova". Usado para criar um novo registro (ex: cadastrar um usuário).\n- **PUT**: "Substitua essa informação". Usado para atualizar um registro inteiro.\n- **PATCH**: "Altere apenas um pedaço da informação". Usado para atualizar apenas campos específicos.\n- **DELETE**: "Apague essa informação".\n- **OPTIONS**: Usado pelos navegadores para checar quais métodos são permitidos (CORS).\n\nUsar os verbos corretamente garante a semântica da API REST e protege os sistemas (um GET acidental repetido não deve criar compras duplicadas, pois é idempotente).',
    'The HTTP Method (also called a verb) indicates the intent of your request. Think of it as the action command.\n\n- **GET**: "Give me this information". Used only for reading. Should not alter the database.\n- **POST**: "Take this new information". Used to create a new record (e.g., register a user).\n- **PUT**: "Replace this information". Used to update an entire record.\n- **PATCH**: "Change just a piece of the information". Used to update specific fields only.\n- **DELETE**: "Erase this information".\n- **OPTIONS**: Used by browsers to check which methods are allowed (CORS).\n\nUsing verbs correctly ensures REST API semantics and protects systems (a repeated accidental GET should not create duplicate purchases, because it is idempotent).',
    'Verbos HTTP, GET, POST, PUT, DELETE, Idempotência',
    'HTTP Verbs, GET, POST, PUT, DELETE, Idempotency',
    'Usar GET passando dados sigilosos na URL (senhas). Usar POST para apenas buscar dados. Usar GET para excluir um item (isso permite que um bot destrua seu sistema apenas acessando links).',
    'Using GET passing sensitive data in the URL (passwords). Using POST just to fetch data. Using GET to delete an item (this allows a bot to destroy your system just by visiting links).',
    'Em um e-commerce: GET /produtos (lista o catálogo), POST /pedidos (finaliza a compra), PATCH /usuarios/1 (muda apenas a foto do perfil).',
    'In an e-commerce: GET /products (lists the catalog), POST /orders (finishes the purchase), PATCH /users/1 (changes only the profile picture).',
    'POST /products HTTP/1.1\nContent-Type: application/json\n\n{\n  "name": "Smartphone",\n  "price": 999.99\n}',
    'POST /products HTTP/1.1\nContent-Type: application/json\n\n{\n  "name": "Smartphone",\n  "price": 999.99\n}',
    'HTTP/1.1 201 Created\n\n{\n  "id": 42,\n  "name": "Smartphone"\n}',
    'HTTP/1.1 201 Created\n\n{\n  "id": 42,\n  "name": "Smartphone"\n}',
    'REST, Segurança, Body JSON',
    'REST, Security, JSON Body',
    'Na próxima missão prática, você deverá escolher o método exato para realizar a ação desejada no servidor simulado. Fique atento se é leitura ou escrita.',
    'In the next practical mission, you must choose the exact method to perform the desired action on the simulated server. Pay attention to whether it is reading or writing.',
    1,
    6,
    (SELECT id FROM missions WHERE slug = 'primeira-requisicao-get')
);

-- 3. Headers e Body JSON
INSERT INTO theory_lessons (
    id, module_id, title, title_en, summary, summary_en, 
    content, content_en, key_concepts, key_concepts_en, 
    common_mistakes, common_mistakes_en, practical_example, practical_example_en, 
    request_example, request_example_en, response_example, response_example_en,
    related_concepts, related_concepts_en, before_mission, before_mission_en, 
    order_index, reading_time_minutes, related_mission_id
) VALUES (
    '44444444-4444-4444-4444-000000000004',
    (SELECT id FROM learning_modules WHERE slug = 'headers-e-body-json'),
    'Headers e Body JSON',
    'Headers and JSON Body',
    'Como as requisições transportam metadados ocultos e grandes blocos de dados através de Headers e do Body.',
    'How requests carry hidden metadata and large chunks of data through Headers and the Body.',
    'As requisições HTTP são divididas em duas partes principais: **Headers** e **Body**.\n\nOs **Headers** são os "metadados" da requisição. Eles vão ocultos e descrevem coisas sobre a mensagem: quem é o navegador (`User-Agent`), qual idioma prefere (`Accept-Language`), ou que formato de dados está enviando (`Content-Type`). Eles funcionam como o selo e o remetente de uma carta.\n\nO **Body** é o corpo da mensagem. É lá que os dados reais da operação viajam. Se você faz um POST para cadastrar um produto, o nome e o preço vão no Body. Hoje em dia, o formato mais comum usado no Body é o **JSON** (JavaScript Object Notation), um formato de texto leve e estruturado com chaves e valores. Para o servidor entender que você enviou um JSON, você obrigatoriamente tem que incluir no Header: `Content-Type: application/json`.',
    'HTTP requests are divided into two main parts: **Headers** and **Body**.\n\nThe **Headers** are the "metadata" of the request. They go hidden and describe things about the message: what the browser is (`User-Agent`), what language it prefers (`Accept-Language`), or what data format it is sending (`Content-Type`). They act like the stamp and sender address of a letter.\n\nThe **Body** is the body of the message. That is where the actual data of the operation travels. If you make a POST to register a product, the name and price go in the Body. Today, the most common format used in the Body is **JSON** (JavaScript Object Notation), a lightweight structured text format with keys and values. For the server to understand that you sent a JSON, you must include in the Header: `Content-Type: application/json`.',
    'Headers, Body, Payload, JSON, Content-Type',
    'Headers, Body, Payload, JSON, Content-Type',
    'Esquecer o header Content-Type, fazendo o servidor rejeitar a requisição 400. Enviar Body em requisições GET (tecnicamente não proibido, mas a maioria dos servidores ignora). Digitar JSON inválido com aspas simples (JSON exige aspas duplas).',
    'Forgetting the Content-Type header, making the server reject the request 400. Sending a Body in GET requests (technically not forbidden, but most servers ignore it). Typing invalid JSON with single quotes (JSON requires double quotes).',
    'Ao preencher um formulário de login e clicar em "Entrar", o seu email e senha vão encapsulados no Body da requisição, e o Header avisa o formato dos dados.',
    'When filling out a login form and clicking "Enter", your email and password go encapsulated in the Body of the request, and the Header warns about the data format.',
    'POST /api/users HTTP/1.1\nContent-Type: application/json\n\n{\n  "email": "user@test.com",\n  "password": "123"\n}',
    'POST /api/users HTTP/1.1\nContent-Type: application/json\n\n{\n  "email": "user@test.com",\n  "password": "123"\n}',
    'HTTP/1.1 200 OK\n\n{\n  "message": "Login successful"\n}',
    'HTTP/1.1 200 OK\n\n{\n  "message": "Login successful"\n}',
    'Autenticação, Métodos HTTP',
    'Authentication, HTTP Methods',
    'Se você for criar algo no Sandbox, não esqueça de usar o botão rápido "Use JSON" para injetar o header corretamente antes de enviar o Body.',
    'If you are going to create something in the Sandbox, do not forget to use the quick "Use JSON" button to properly inject the header before sending the Body.',
    1,
    7,
    (SELECT id FROM missions WHERE slug = 'post-com-json')
);

-- 4. Status Codes
INSERT INTO theory_lessons (
    id, module_id, title, title_en, summary, summary_en, 
    content, content_en, key_concepts, key_concepts_en, 
    common_mistakes, common_mistakes_en, practical_example, practical_example_en, 
    request_example, request_example_en, response_example, response_example_en,
    related_concepts, related_concepts_en, before_mission, before_mission_en, 
    order_index, reading_time_minutes, related_mission_id
) VALUES (
    '44444444-4444-4444-4444-000000000005',
    (SELECT id FROM learning_modules WHERE slug = 'status-codes'),
    'Status Codes da Resposta',
    'Response Status Codes',
    'O dicionário de respostas da web. Entenda o que os números 200, 404 e 500 significam.',
    'The web dictionary of responses. Understand what numbers 200, 404, and 500 mean.',
    'O Status Code é um número de três dígitos que o servidor retorna na Response, resumindo o que aconteceu com a sua requisição. Eles são divididos em famílias:\n\n- **2xx (Sucesso)**: Tudo ocorreu bem. `200 OK` (Busca com sucesso) ou `201 Created` (Criado com sucesso).\n- **3xx (Redirecionamento)**: O recurso mudou de lugar. Vá para outra URL.\n- **4xx (Erro do Cliente)**: VOCÊ fez algo errado. `400 Bad Request` (Esqueceu algum campo obrigatório ou errou o JSON), `401 Unauthorized` (Faltou senha/token), `404 Not Found` (Rota ou ID não existe).\n- **5xx (Erro do Servidor)**: O SERVIDOR quebrou. `500 Internal Server Error` (Bug no código do backend) ou `502 Bad Gateway`.\n\nSistemas modernos usam o Status Code para decidir a interface: se vem 200, exibe verde. Se vem 400, exibe um alerta vermelho pro usuário.',
    'The Status Code is a three-digit number the server returns in the Response, summarizing what happened to your request. They are divided into families:\n\n- **2xx (Success)**: Everything went well. `200 OK` (Fetch successful) or `201 Created` (Created successfully).\n- **3xx (Redirection)**: The resource moved. Go to another URL.\n- **4xx (Client Error)**: YOU did something wrong. `400 Bad Request` (Forgot a mandatory field or messed up the JSON), `401 Unauthorized` (Missing password/token), `404 Not Found` (Route or ID does not exist).\n- **5xx (Server Error)**: The SERVER broke. `500 Internal Server Error` (Backend code bug) or `502 Bad Gateway`.\n\nModern systems use the Status Code to decide the interface: if 200 comes back, it displays green. If 400 comes back, it displays a red alert for the user.',
    'Status Codes, Erros do Cliente (4xx), Erros do Servidor (5xx)',
    'Status Codes, Client Errors (4xx), Server Errors (5xx)',
    'Retornar "200 OK" mesmo quando ocorre um erro na regra de negócio (prática terrível que quebra bibliotecas de frontend). Confundir 401 (Não tem login) com 403 (Tem login, mas não tem permissão para a ação).',
    'Returning "200 OK" even when a business logic error occurs (terrible practice that breaks frontend libraries). Confusing 401 (No login) with 403 (Logged in, but no permission for the action).',
    'Tentar acessar o perfil de um usuário excluído: O app faz GET /users/99 e recebe um 404 Not Found. O app então redireciona você para a tela "Perfil Inexistente".',
    'Trying to access the profile of a deleted user: The app does GET /users/99 and receives a 404 Not Found. The app then redirects you to the "Profile Inexistent" screen.',
    'POST /products HTTP/1.1\nContent-Type: application/json\n\n{}',
    'POST /products HTTP/1.1\nContent-Type: application/json\n\n{}',
    'HTTP/1.1 400 Bad Request\n\n{\n  "error": "Field ''name'' is mandatory"\n}',
    'HTTP/1.1 400 Bad Request\n\n{\n  "error": "Field ''name'' is mandatory"\n}',
    'REST, Tratamento de Erros, Resiliência',
    'REST, Error Handling, Resilience',
    'Na próxima missão, identifique qual código o Sandbox retorna dependendo do seu payload. Use isso como um diagnóstico.',
    'In the next mission, identify which code the Sandbox returns depending on your payload. Use it as a diagnosis.',
    1,
    5,
    (SELECT id FROM missions WHERE slug = 'status-code-criacao')
);

-- 5. Autenticação Bearer Token
INSERT INTO theory_lessons (
    id, module_id, title, title_en, summary, summary_en, 
    content, content_en, key_concepts, key_concepts_en, 
    common_mistakes, common_mistakes_en, practical_example, practical_example_en, 
    request_example, request_example_en, response_example, response_example_en,
    related_concepts, related_concepts_en, before_mission, before_mission_en, 
    order_index, reading_time_minutes, related_mission_id
) VALUES (
    '44444444-4444-4444-4444-000000000006',
    (SELECT id FROM learning_modules WHERE slug = 'autenticacao-bearer-token'),
    'Autenticação e Bearer Token',
    'Authentication and Bearer Token',
    'Como as APIs sabem quem você é. O uso do cabeçalho Authorization para proteger rotas.',
    'How APIs know who you are. The use of the Authorization header to protect routes.',
    'APIs públicas permitem acesso de qualquer pessoa. APIs privadas precisam verificar sua identidade. O padrão mais moderno e utilizado no mundo hoje é o envio de Tokens (como o JWT) através de Headers HTTP.\n\nQuando você faz login num sistema, a API devolve uma string embaralhada (o Token). A partir daí, toda requisição que você quiser fazer para acessar dados privados deve incluir esse token no header `Authorization` usando o formato `Bearer <seu_token>`.\n\nSe o token faltar, expirar ou estiver adulterado, o servidor retornará imediatamente um erro **401 Unauthorized**.\n\nAviso de segurança crítico: tokens de API nunca devem ser colocados diretamente na URL (ex: ?token=123), pois URLs ficam salvas nos logs dos navegadores e servidores, permitindo o roubo da sua sessão.',
    'Public APIs allow access from anyone. Private APIs need to verify your identity. The most modern and widely used standard in the world today is sending Tokens (like JWT) through HTTP Headers.\n\nWhen you log into a system, the API returns a scrambled string (the Token). From then on, every request you want to make to access private data must include this token in the `Authorization` header using the `Bearer <your_token>` format.\n\nIf the token is missing, expired, or tampered with, the server will immediately return a **401 Unauthorized** error.\n\nCritical security warning: API tokens should never be placed directly in the URL (e.g., ?token=123), because URLs are saved in browser and server logs, allowing your session to be stolen.',
    'Autenticação, JWT, Bearer Token, Header Authorization, HTTP 401',
    'Authentication, JWT, Bearer Token, Authorization Header, HTTP 401',
    'Esquecer a palavra "Bearer " antes do token no header. Mandar o token no body de um GET. Expor o token no frontend permanentemente.',
    'Forgetting the word "Bearer " before the token in the header. Sending the token in the body of a GET. Exposing the token permanently in the frontend.',
    'Você entra no Instagram. O app ganha um token. Depois, ao arrastar a tela para carregar novas fotos, o app usa esse token oculto no Header para provar para a API do Instagram que a requisição está vindo da sua conta autêntica.',
    'You log into Instagram. The app gets a token. Later, when you pull to refresh new photos, the app uses this hidden token in the Header to prove to the Instagram API that the request is coming from your authentic account.',
    'GET /api/user/profile HTTP/1.1\nAuthorization: Bearer demo-token-12345',
    'GET /api/user/profile HTTP/1.1\nAuthorization: Bearer demo-token-12345',
    'HTTP/1.1 200 OK\n\n{\n  "user": "Alice",\n  "role": "admin"\n}',
    'HTTP/1.1 200 OK\n\n{\n  "user": "Alice",\n  "role": "admin"\n}',
    'Segurança, JWT, Sessões Stateless',
    'Security, JWT, Stateless Sessions',
    'Vá para o Sandbox e faça o teste. Tente bater na rota `/secure` sem token e veja a porta fechar na sua cara. Depois, use o botão de injetar Demo Token e veja a mágica.',
    'Go to the Sandbox and test it. Try hitting the `/secure` route without a token and watch the door slam in your face. Then, use the inject Demo Token button and see the magic.',
    1,
    6,
    (SELECT id FROM missions WHERE slug = 'fluxo-requisicao-autenticada')
);

-- 6. Debug de Erros
INSERT INTO theory_lessons (
    id, module_id, title, title_en, summary, summary_en, 
    content, content_en, key_concepts, key_concepts_en, 
    common_mistakes, common_mistakes_en, practical_example, practical_example_en, 
    request_example, request_example_en, response_example, response_example_en,
    related_concepts, related_concepts_en, before_mission, before_mission_en, 
    order_index, reading_time_minutes, related_mission_id
) VALUES (
    '44444444-4444-4444-4444-000000000007',
    (SELECT id FROM learning_modules WHERE slug = 'debug-de-erros'),
    'Mentalidade de Debug',
    'Debugging Mindset',
    'Como ler as mensagens de erro das APIs e consertar suas requisições sem frustração.',
    'How to read API error messages and fix your requests without frustration.',
    'APIs não leem mentes. Se uma API quebrar, ela geralmente tenta te avisar o porquê através do Response. Debuggar APIs é uma habilidade investigativa.\n\nSe você receber um erro, siga o checklist:\n1. **Olhe o Status Code**: Foi 4xx? A culpa é sua. Foi 5xx? A culpa é do Backend.\n2. **Leia o Response Body**: Muitas APIs mandam uma mensagem detalhada do tipo "O campo X é obrigatório" ou "Token expirado".\n3. **Verifique o Path**: Você digitou `/produtos` em vez de `/products`? (Isso gera 404).\n4. **Verifique o Método**: Você fez um POST para deletar? (Isso gera 405 Method Not Allowed).\n5. **Verifique o Body**: As aspas estão corretas no JSON?\n6. **Verifique os Headers**: Esqueceu o `Authorization`?\n\nA maior habilidade de um programador não é não errar, mas saber ler o erro que acabou de acontecer.',
    'APIs do not read minds. If an API breaks, it usually tries to tell you why through the Response. Debugging APIs is an investigative skill.\n\nIf you get an error, follow the checklist:\n1. **Look at the Status Code**: Was it 4xx? It is your fault. Was it 5xx? It is the Backend is fault.\n2. **Read the Response Body**: Many APIs send a detailed message like "Field X is mandatory" or "Token expired".\n3. **Check the Path**: Did you type `/produtos` instead of `/products`? (This generates 404).\n4. **Check the Method**: Did you make a POST to delete? (This generates 405 Method Not Allowed).\n5. **Check the Body**: Are the quotes correct in the JSON?\n6. **Check the Headers**: Forgot the `Authorization`?\n\nThe greatest skill of a programmer is not avoiding mistakes, but knowing how to read the error that just happened.',
    'Troubleshooting, Error Tracking, Diagnóstico, Console do Navegador',
    'Troubleshooting, Error Tracking, Diagnostics, Browser Console',
    'Ficar testando códigos aleatórios antes de ler o Response Body. Culpar a API por um 400 Bad Request sem checar a vírgula no próprio JSON.',
    'Testing random code before reading the Response Body. Blaming the API for a 400 Bad Request without checking the comma in your own JSON.',
    'A requisição falhou. Em vez de adivinhar, o desenvolvedor abre o DevTools (F12) no navegador, clica na aba Network, seleciona a requisição vermelha e analisa o campo "Response" para ver a mensagem exata do erro que a API mandou.',
    'The request failed. Instead of guessing, the developer opens DevTools (F12) in the browser, clicks the Network tab, selects the red request, and analyzes the "Response" field to see the exact error message the API sent.',
    'POST /products HTTP/1.1\nContent-Type: application/json\n\n{\n  name: "Sem aspas na chave"\n}',
    'POST /products HTTP/1.1\nContent-Type: application/json\n\n{\n  name: "No quotes on the key"\n}',
    'HTTP/1.1 400 Bad Request\n\n{\n  "error": "Malformed JSON. Parse error at line 2."\n}',
    'HTTP/1.1 400 Bad Request\n\n{\n  "error": "Malformed JSON. Parse error at line 2."\n}',
    'Status Codes, JSON Validation, Network Tools',
    'Status Codes, JSON Validation, Network Tools',
    'O Sandbox foi programado para rejeitar requisições malformadas. Na missão "Corrija um erro 400", use as dicas do Body para encontrar a falha.',
    'The Sandbox was programmed to reject malformed requests. In the "Fix a 400 error" mission, use the hints in the Body to find the flaw.',
    1,
    8,
    (SELECT id FROM missions WHERE slug = 'corrija-erro-400')
);
